#!/bin/sh

if [ "$1" = "autoconf" ]; then
    if [ -x /usr/sbin/faxstat ]; then
        echo yes
        exit 0
    else
        echo no
        exit 1
    fi
fi

if [ "$1" = "config" ]; then
        echo 'graph_title Fax in queue'
        echo 'graph_args --base 1000 -l 0'
        echo 'graph_vlabel faxs'
        echo 'graph_noscale true'
        echo 'graph_info Hylafax queue'
        echo 'graph_category hylafax'
        echo 'queue.label queue'
        echo 'queue.type GAUGE'
        echo 'queue.info queue'
        exit 0
fi

echo "queue.value "$(faxstat -sa| grep '^[0-9].*' |wc -l)
