#!/bin/sh
#
# add this into munin/plugin-conf.d/plugins.conf:
# 
# [asterisk_inuse]
# user root
#

if [ "$1" = "autoconf" ]; then
    if [ -x /usr/sbin/asterisk ]; then
        /usr/sbin/asterisk -rx 'sip show inuse' > /dev/null
        if [ $? = "0" ]; then
                echo yes
                exit 0
        else
                    echo no
                    exit 1
            fi
    else
        echo no
        exit 1
    fi
fi

if [ "$1" = "config" ]; then
        echo 'graph_title Line use'
        echo 'graph_args --base 1000 -l 0'
        echo 'graph_vlabel Concurrent calls'
        echo 'graph_noscale true'
        echo 'graph_info Asterisk concurrent calls'
        echo 'graph_category asterisk'
        echo 'inuse.label inuse'
        echo 'inuse.type GAUGE'
        echo 'inuse.info concurrent calls'
        exit 0
fi

INUSE=`/usr/sbin/asterisk -rx 'sip show channels' | grep 'active SIP' | awk '{print $1}'`
echo "inuse.value "$INUSE
